<?php
 // module/Usuario/view/usuario/usuario/add.phtml:

 $title = 'Add new usuario';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('usuario', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('nombre'));
 echo $this->formRow($form->get('cve_usuario'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();