<?php
 // module/Usuario/view/usuario/usuario/index.phtml:

 $title = 'Mis Usuarios';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('usuario', array('action'=>'add'));?>">Add new usuario</a>
 </p>

 <table class="table">
 <tr>
     <th>Clave Usuario</th>
     <th>Nombre</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($usuarios as $usuario) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($usuario->cve_usuario);?></td>
     <td><?php echo $this->escapeHtml($usuario->nombre);?></td>
     <td>
         <a href="<?php echo $this->url('usuario',
             array('action'=>'edit', 'id' => $usuario->id));?>">Edit</a>
         <a href="<?php echo $this->url('usuario',
             array('action'=>'delete', 'id' => $usuario->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>